WITH seed_apps(app_code) AS (
    VALUES
        ('stellaxis.identity.access.login.api'),
        ('stellaxis.identity.access.session.api'),
        ('stellaxis.identity.access.token.worker'),
        ('stellaxis.identity.access.sso.adapter'),
        ('stellaxis.identity.account.profile.api'),
        ('stellaxis.identity.account.permission.api'),
        ('stellaxis.identity.account.role.api'),
        ('stellaxis.identity.audit.authlog.worker'),
        ('stellaxis.ecommerce.catalog.product.api'),
        ('stellaxis.ecommerce.catalog.category.api'),
        ('stellaxis.ecommerce.catalog.search.api'),
        ('stellaxis.ecommerce.pricing.price.api'),
        ('stellaxis.ecommerce.pricing.promotion.api'),
        ('stellaxis.ecommerce.cart.cart.api'),
        ('stellaxis.ecommerce.order.checkout.api'),
        ('stellaxis.ecommerce.order.order.api'),
        ('stellaxis.ecommerce.order.fulfillment.worker'),
        ('stellaxis.ecommerce.order.refund.api'),
        ('stellaxis.ecommerce.inventory.stock.api'),
        ('stellaxis.ecommerce.inventory.reservation.worker'),
        ('stellaxis.payment.account.wallet.api'),
        ('stellaxis.payment.account.ledger.api'),
        ('stellaxis.payment.risk.antifraud.api'),
        ('stellaxis.payment.risk.antifraud-worker.worker'),
        ('stellaxis.payment.channel.gateway.api'),
        ('stellaxis.payment.channel.bank-adapter.adapter'),
        ('stellaxis.payment.settlement.settlement.job'),
        ('stellaxis.payment.reconciliation.reconcile.job'),
        ('stellaxis.finance.accounting.journal.api'),
        ('stellaxis.finance.accounting.invoice.api'),
        ('stellaxis.finance.accounting.tax.api'),
        ('stellaxis.finance.treasury.cashflow.api'),
        ('stellaxis.finance.treasury.payment-plan.job'),
        ('stellaxis.finance.report.financial-report.api'),
        ('stellaxis.crm.customer.profile.api'),
        ('stellaxis.crm.customer.segment.api'),
        ('stellaxis.crm.customer.contact.api'),
        ('stellaxis.crm.sales.lead.api'),
        ('stellaxis.crm.sales.opportunity.api'),
        ('stellaxis.crm.sales.contract.api'),
        ('stellaxis.crm.service.ticket.api'),
        ('stellaxis.crm.service.sla-worker.worker'),
        ('stellaxis.marketing.campaign.campaign.api'),
        ('stellaxis.marketing.campaign.coupon.api'),
        ('stellaxis.marketing.automation.email-worker.worker'),
        ('stellaxis.marketing.automation.sms-worker.worker'),
        ('stellaxis.marketing.analytics.attribution.api'),
        ('stellaxis.marketing.analytics.conversion.job'),
        ('stellaxis.supplychain.procurement.purchase-order.api'),
        ('stellaxis.supplychain.procurement.supplier.api'),
        ('stellaxis.supplychain.planning.demand-forecast.job'),
        ('stellaxis.supplychain.planning.supply-plan.api'),
        ('stellaxis.supplychain.transport.shipment.api'),
        ('stellaxis.supplychain.transport.carrier-adapter.adapter'),
        ('stellaxis.logistics.delivery.dispatch.api'),
        ('stellaxis.logistics.delivery.route-planner.api'),
        ('stellaxis.logistics.delivery.tracking.api'),
        ('stellaxis.logistics.delivery.proof-worker.worker'),
        ('stellaxis.warehouse.inbound.receiving.api'),
        ('stellaxis.warehouse.inbound.putaway.worker'),
        ('stellaxis.warehouse.outbound.picking.api'),
        ('stellaxis.warehouse.outbound.packing.api'),
        ('stellaxis.warehouse.outbound.shipping.worker'),
        ('stellaxis.warehouse.inventory.cycle-count.job'),
        ('stellaxis.hr.employee.profile.api'),
        ('stellaxis.hr.employee.onboarding.api'),
        ('stellaxis.hr.employee.attendance.api'),
        ('stellaxis.hr.payroll.salary.api'),
        ('stellaxis.hr.payroll.benefit.api'),
        ('stellaxis.hr.recruiting.candidate.api'),
        ('stellaxis.procurement.sourcing.rfq.api'),
        ('stellaxis.procurement.sourcing.bid-evaluation.worker'),
        ('stellaxis.procurement.contract.contract.api'),
        ('stellaxis.procurement.contract.approval-workflow.worker'),
        ('stellaxis.procurement.supplier.supplier-risk.api'),
        ('stellaxis.legal.contract.review.api'),
        ('stellaxis.legal.compliance.policy.api'),
        ('stellaxis.legal.compliance.audit-job.job'),
        ('stellaxis.security.iam.access-policy.api'),
        ('stellaxis.security.iam.key-rotation.job'),
        ('stellaxis.security.soc.alert.api'),
        ('stellaxis.security.soc.incident-response.worker'),
        ('stellaxis.security.vulnerability.scan-job.job'),
        ('stellaxis.platform.config.config-center.api'),
        ('stellaxis.platform.registry.service-registry.api'),
        ('stellaxis.platform.gateway.api-gateway.api'),
        ('stellaxis.platform.workflow.approval-engine.api'),
        ('stellaxis.platform.scheduler.job-scheduler.api'),
        ('stellaxis.platform.feature.flag-service.api'),
        ('stellaxis.platform.notification.notification-api.api'),
        ('stellaxis.data.ingestion.batch-ingest.job'),
        ('stellaxis.data.ingestion.stream-ingest.worker'),
        ('stellaxis.data.catalog.metadata.api'),
        ('stellaxis.data.quality.rule-engine.api'),
        ('stellaxis.data.warehouse.table-lineage.api'),
        ('stellaxis.data.analytics.metric-service.api'),
        ('stellaxis.observability.metrics.metric-gateway.api'),
        ('stellaxis.observability.logs.log-indexer.worker'),
        ('stellaxis.observability.tracing.trace-query.api'),
        ('stellaxis.observability.alerting.alert-manager.api')
),
normalized AS (
    SELECT app_code,
           split_part(app_code, '.', 1) AS organization,
           split_part(app_code, '.', 2) AS business_domain,
           split_part(app_code, '.', 3) AS capability_domain,
           split_part(app_code, '.', 4) AS application_name,
           split_part(app_code, '.', 5) AS role,
           'prod' AS environment,
           'active' AS status,
           'managed' AS lifecycle
    FROM seed_apps
),
prepared AS (
    SELECT app_code,
           organization,
           business_domain,
           capability_domain,
           application_name,
           role,
           environment,
           status,
           lifecycle,
           concat(
               initcap(replace(business_domain, '-', ' ')),
               ' ',
               initcap(replace(capability_domain, '-', ' ')),
               ' ',
               initcap(replace(application_name, '-', ' ')),
               ' ',
               upper(role)
           ) AS app_name,
           concat(business_domain, '-platform') AS owner_team_code,
           concat(initcap(replace(business_domain, '-', ' ')), ' Platform') AS owner_team_name,
           CASE
               WHEN role = 'adapter' THEN 'java'
               ELSE 'go'
           END AS language,
           concat('https://git.example.com/', replace(app_code, '.', '/')) AS repository_url,
           jsonb_build_object(
               'organization', organization,
               'business_domain', business_domain,
               'capability_domain', capability_domain,
               'role', role,
               'seed', 'enterprise-apps'
           ) AS labels
    FROM normalized
),
upsert_ci AS (
    INSERT INTO ci_core (
        ci_type,
        ci_code,
        ci_name,
        display_name,
        status,
        lifecycle,
        environment,
        source_system,
        external_id,
        labels,
        deleted_at
    )
    SELECT 'application',
           app_code,
           app_name,
           app_name,
           status,
           lifecycle,
           environment,
           'enterprise-apps.sql',
           app_code,
           labels,
           NULL
    FROM prepared
    ON CONFLICT (ci_type, ci_code, environment) DO UPDATE
    SET ci_name = EXCLUDED.ci_name,
        display_name = EXCLUDED.display_name,
        status = EXCLUDED.status,
        lifecycle = EXCLUDED.lifecycle,
        source_system = EXCLUDED.source_system,
        external_id = EXCLUDED.external_id,
        labels = EXCLUDED.labels,
        deleted_at = NULL,
        updated_at = now()
    RETURNING ci_id, ci_code
)
INSERT INTO app_read_model (
    app_id,
    app_code,
    app_name,
    environment,
    status,
    lifecycle,
    owner_team_code,
    owner_team_name,
    language,
    repository_url,
    cache_version,
    updated_at
)
SELECT ci.ci_id,
       p.app_code,
       p.app_name,
       p.environment,
       p.status,
       p.lifecycle,
       p.owner_team_code,
       p.owner_team_name,
       p.language,
       p.repository_url,
       1,
       now()
FROM prepared p
JOIN upsert_ci ci ON ci.ci_code = p.app_code
ON CONFLICT (app_id) DO UPDATE
SET app_code = EXCLUDED.app_code,
    app_name = EXCLUDED.app_name,
    environment = EXCLUDED.environment,
    status = EXCLUDED.status,
    lifecycle = EXCLUDED.lifecycle,
    owner_team_code = EXCLUDED.owner_team_code,
    owner_team_name = EXCLUDED.owner_team_name,
    language = EXCLUDED.language,
    repository_url = EXCLUDED.repository_url,
    cache_version = app_read_model.cache_version + 1,
    updated_at = now();
